repositoryUrl: https://github.com/dynamsoft-docs/code-parser-docs-js/blob/main
repository: dynamsoft-docs/code-parser-docs-js
docFullPath: https://www.dynamsoft.com/code-parser/docs/web
firstLevelUrl: /code-parser/docs/web/
docHomePage: /code-parser/docs/core/introduction/

js: /code-parser/docs/web/programming/javascript/
dcp_js_api: /code-parser/docs/web/programming/javascript/api-reference/
dcp_enum: /code-parser/docs/web/programming/javascript/api-reference/enum/
js_release_notes: /code-parser/docs/web/programming/javascript/release-notes/

dcv_enumerations: /capture-vision/docs/core/enums/

dcv_js_api: /capture-vision/docs/web/programming/javascript/api-reference/
dcv_introduction: /capture-vision/docs/core/introduction/

assets: /code-parser/docs/web/assets/
edit_icon: /code-parser/docs/web/assets/img-icon/edit-icon.png
smile_icon: /code-parser/docs/web/assets/img-icon/icon-smile.png
sad_icon: /code-parser/docs/web/assets/img-icon/icon-sad.png
dbr_icon: /code-parser/docs/web/assets/img-icon/icon-dbr.svg
dwt_icon: /code-parser/docs/web/assets/img-icon/icon-dwt.svg
dnt_icon: /code-parser/docs/web/assets/img-icon/icon-dnt.svg

release_notes: /code-parser/docs/core/release-notes/
code_types: /code-parser/docs/core/code-types/

useVersionTree: true

baseurl: "/code-parser/docs/web"
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-webp
  - jekyll-relative-links
  - jekyll-redirect-from
  - jekyll-readme-index
  - jekyll-seo-tag


defaults:
  - scope:
      path: ""
    values:
      layout: "default-layout"
      noTitleIndex: true
      needAutoGenerateSidebar: true
      needGenerateH3Content: true
  - scope: 
      path: "programming/javascript" 
    values: 
      docRootName: "Code Parser JS Edition" 
      docHomePage: "/code-parser/docs/web/programming/javascript/"
  - scope:
      path: "Hide_Tree_Page.html"
    values:
      sitemap: false

edition: js

url: "https://www.dynamsoft.com" # sitemap root

